"""add_exam_rooms

Revision ID: 4102e04c27c4
Revises: bd0dc90295ee
Create Date: 2026-03-10 15:23:37.638359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4102e04c27c4'
down_revision: Union[str, None] = 'bd0dc90295ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_code', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    op.drop_column('students', 'student_code')
    # ### end Alembic commands ###